[package]
name = "openwurli"
version = "0.1.0"
edition = "2024"
description = "Wurlitzer 200A virtual instrument â€” CLAP and VST3 plugin"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
openwurli-dsp = { path = "../openwurli-dsp" }
